gpt-4o:
  OPENAI_API_BASE: 
  OPENAI_API_KEY: 
  OPENAI_API_MODEL: "gpt-4o"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10
gpt-4v:
  OPENAI_API_BASE: 
  OPENAI_API_KEY: "sk-"
  OPENAI_API_MODEL: "gpt-4v"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10
gpt-4v-1:
  OPENAI_API_BASE: 
  OPENAI_API_KEY: "sk-"
  OPENAI_API_MODEL: "gpt-4v"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10
qwen3.5-flash:
  OPENAI_API_BASE: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  OPENAI_API_KEY: "sk-53a39b3ab47f41feae388b36b557528a"
  OPENAI_API_MODEL: "qwen3.5-flash"
  MAX_TOKENS: 300
  TEMPERATURE: 0.0
  REQUEST_INTERVAL: 10